### ISSUE TITLE
Calling .back() first

### ISSUE THREAD

**Issue by florianziegler** [qodesmith/typer#17]
Hi! First of all, thanks for your great work!

My isse: Do I always have to start using typer by calling the `line` method first?

When I try using this

```
<p>This <span class="typing">initial string</span> looks good.</p>

<script>
typer( '.typing', 100 )
	.back( 14 )
	.pause( 100 )
	.continue( 'new string' );
</script>
``` 

nothing happens.

I would like to delete existing text, then – and without adding a new line – add text.

Not sure this is a bug or a feature. :)

**Comment by qodesmith** [comment]
@florianziegler Interesting use case. Typer isn't built to play with pre-existing content. So you don't have to start with `.line`, however, if you want anything typed on the screen, a `.line` would have to come before a `.continue` since Typer creates all the elements it types in. Let me look into seeing how I can implement what you're trying to do. I'll get back to you.

**Comment by qodesmith** [comment]
I don't think this is going to be a viable option. Dealing with pre-existing content is tricky. It can be something simple as just some text or as complex as an entire webpage. I'm going to close this issue but perhaps if I can think of an intuitive way I'll implement it in the future.
