### ISSUE TITLE
Typer seemingly breaking (using Vue.js)

### ISSUE THREAD

**Issue by scitronboy** [qodesmith/typer#29]
So I have completely no idea why I can't get this to work, even though I am sure it's just some small thing I'm missing. So my app uses Vue.js, and in my mounted (setup) function I have this:

```javascript
import typer from 'typer-js'

...

this.inputStatus = typer('#statusRef', { speed: 20 })
.cursor({ block: true })
.line('WAITING_FOR_INPUT')
```

So this works fine, as do all the commands if I place them in the mounted function. However, after the commands finish executing, I later call `.line('...')` on `this.inputStatus` in a Vue keydown handler function. It does not seem to work at all, and neither do any of the other commands. They all work initially in the first function but not later in subsequent functions.

Both functions have the same `this` context and I have verified that at the time when I call `.line()` `this.inputStatus` is an object with line, continue, empty, etc. functions. The surrounding code does execute. There are also no errors in the console. So I really have no idea what could be breaking this, but hopefully, someone can remind me of whatever I'm forgetting. I can also share all the code if needed.

**Comment by qodesmith** [comment]
Hey @scitronboy. So I don't think you're doing anything wrong. My guess is that you're calling `this.inputStatus.line(...)` _later_ - i.e., time has passed since the _first_ set of instructions have _completed_. The way I initially designed this library was to have Typer complete it's run, then quit. Basically, internally, Typer iterates through a series of commands (.line, .back, .continue, etc.). Each time you call a method, it adds it to the queue. Once it reaches the end of the queue, the iteration stops. You can see that in the code [here](https://github.com/qodesmith/typer/blob/master/src/typer.js#L297-L300).

This is the reason you still have an object with all the methods to call. It might be time for me to think about changing this under-the-hood behavior. Essentially, you can "tack on" more method calls, so long as the first set of instructions hasn't completed yet. But once Typer reaches the end of its queue internally, it doesn't have a way to know somebody pushed more instructions into the queue.

**_But not all is lost!_**

`.listen` to the rescue! `.listen` essentially pauses Typer's internal queue until it hears an event broadcast with whatever name you passed into it. While it's in the "listening" state, you can sneak in all the instructions you want!

Change your initial instructions to include a `.listen` call:

```javascript
this.inputStatus = typer('#statusRef', { speed: 20 })
  .cursor({ block: true })
  .line('WAITING_FOR_INPUT')
  .listen('my-custom-event-name') // Add THIS line!
```



Then later in your code, you can continue where you left off _and_ add more instructions like so:

```javascript
// First, add all the instructions you want.
this.inputStatus
  .line('Look, it works!')
  .line('I can add whatever I want here.')

// Second, dispatch a custom event from the `document.body`
// with the same value you used before.
// This will trigger Typer to pick up from where it last left off.
document.body.dispatchEvent(new Event('my-custom-event-name'))
```

Let me know if you still have an issue with this.

**Comment by scitronboy** [comment]
I see. I was wondering if it was something like that. Thanks so much for the detailed response!
