### ISSUE TITLE
UglifyJs error

### ISSUE THREAD

**Issue by ohadnav** [qodesmith/typer#3]
A) This tool is awesome!
B) There seems to be an error when compiling typer-npm.js to es5.
I get the following error when running `webpack -p`

> ERROR in bundle.js from UglifyJs
> SyntaxError: Unexpected token: name (q) [./~/typer-js/typer-npm.js:24,0]

My webpack config module part:
```
module  : {
        loaders: [
            {
                test   : /\.js$/,
                exclude: /(node_modules|bower_components)/,
                loader : 'babel-loader',
                query  : {
                    presets: ['es2015']
                }
            }
        ]
    },
```
Happy new year :)

**Comment by qodesmith** [comment]
@ohadnav Happy new year my friend! I'm glad you like the Typer.js library. Ok, so admittedly, I'm no Webpack expert. Hell, I'm not even a Webpack novice! None the less, I've run into my fair share of issues with Uglify and I've seen the error you're running into.

It looks like your build process is trying to uglify the code _before_ it's been transpiled to ES5. In the code, the 1st bit of ES6 is the `let q = [];` line. Uglify.js doesn't know how to parse that (since it's ES6) and will throw the error you're seeing. My suggestion is to look into your Webpack setup and check the order of things that are running. Either that, or Babel for some reason isn't actually transpiling the code down to ES5 so that by the time it hits Uglify we get the error.

Keep me posted in what goes down.

**Comment by ohadnav** [comment]
Wow! thanks for such a quick (and witty) reply!
I totally agree it seems like the order of the build process is messed up.

Will let you know my solution as soon as I'll have it.

btw, what is The Qodesmith working on these days? :)

**Comment by qodesmith** [comment]
@ohadnav Awesome. Post your solution if you find one just in case other's in the future might find it helpful. And my latest project has been the site at [freestylefam.com](http://freestylefam.com). the code isn't open-source (yet), but it's a Backbone front-end sitting on Node/Express on the back with MongoDB for the win. I used to rap (as in, I used to dream of a career) prior to switching to web development back in early 2015. Now that things have "settled" a bit, I think it might be time for some music :)

**Comment by qodesmith** [comment]
And I know that there might not be much to see for the site yet, but as you can see, there's the countdown happening till 2/1/2017. At that point, it will automatically go live. Just sayin...

**Comment by ohadnav** [comment]
haha, I'm already excited ;)
good luck!

I love the javascript rapper story! sounds courageous.
My story is special forces => google => starting my own thing
<http://brainpal.io> (a.k.a writing bugs in javascript)

**Comment by qodesmith** [comment]
@ohadnav Special forces! Sounds elite :) Good luck with brainpal also.

Just in case you don't find a solution (or you just want to move ahead right away), there is already an included minified version - `typer.min.js`. I'm going to close this issue, but if you do find a solution, don't forget to post it here for others to see. Thanks!

**Comment by ohadnav** [comment]
Solved by deleting `typer-npm.js` and adding 
`module.exports = typer;` to `typer.js`
