### ISSUE TITLE
Looping array infinitely 

### ISSUE THREAD

**Issue by engin-can** [qodesmith/typer#34]
Hi, great plugin! I was wondering how I can create an infinite loop for an array of words with a 1 sec delay. I would like to have the typer inline.

`<div>Hello <span class="typer">[ARRAY OF WORDS]</span></div>`

**Comment by qodesmith** [comment]
So I played around with this a bit and I see some improvements I can make to the [repeat](https://github.com/qodesmith/typer#repeat) method. In any case, here's the solution I came up with:

```javascript
function runTyper() {
  // An array of words we want Typer to repeatedly type.
  const words = ['world!', 'JavaScript!', 'engin-can!']

  /*
    Initialize the instance but store it in a variable for later access.
    DO NOT use the class name "typer". That will cause conflicts with the
    cursor styles.

    Since Typer creates it's own <div> to type content into, we start off with
    a single `.line` so as to create the "container". This ensures Typer will
    only create 1 <div> throughout our repeated process.
  */
  const instance = typer('.typer-content').cursor({block: true}).line()

  /*
    We loop over the words here so we can dynamically call methods on the
    instance. Otherwise, we would only be left with having to explicitly call
    these methods manually for each word.
  */
  words.forEach(word => {
    instance
      /*
        Since we used `.line` above, we can now use `.continue` to re-use the
        <div> container Typer created, saving us the layout hassle of Typer
        creating new <div>'s for each word.
      */
      .continue(word)
      .pause(1000) // Pause for 1 second after each word is typed.
      .back('all') // Erase that word, leaving a blank slate for the next one.
  })

  /*
    Return the instance in case we want to call other methods, such as `.kill`.
    We'll use `.repeat` to continue our sequence. In this example, the sequence
    will repeat forever. You can pass a number instead if you want to limit it.
    The boolean 2nd argument signals that we want to empty the container before
    we begin typing again. If we don't, straggler `<div>`'s would be left behind
    because we're repeating the `.line` method from above!
  */
  return instance.repeat(Infinity, true)
}
```

And here's what it potentially looks like (don't mind the dark theme, this is just a demo app I created using [create-new-app](https://github.com/qodesmith/create-new-app)):

https://user-images.githubusercontent.com/11034792/110330162-74e2e100-7feb-11eb-94ad-711767799abe.mov

2 things I want to point out to you:
1. *DON'T* use the class name `typer` on anything. This will cause conflicts with the cursor styles from this library. As you'll see in my example, I used `typer-content` instead.
2. In the html structure you gave me above, I see that you're trying to have Typer type inside a `<span>`. I get what you're trying to do, but since Typer creates its own `<div>`'s to type in (it will create a `<div>` *inside* that `<span>`, if you want things to look right you'll have to add these styles to your app:

```css
.typer-content > div {
  display: inline-block;
}
```

And lastly, I want to point out that I encapsulated everything in the `runTyper` function. You should only call this function once, otherwise Typer will try to initialize on the same element twice and throw an error:

```javascript
const instance = runTyper()
```

And if you want to kill the instance later to let's say navigate to a new page or something, simply run:
```javascript
instance.kill()
```

**Comment by engin-can** [comment]
Thanks, this helps!!
