### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by sbeleidy** [qodesmith/typer#8]
Any chance you could add typer.js to bower?

Here's a link on [how to do that](https://bower.io/docs/creating-packages/) if you're unfamiliar.

**Comment by qodesmith** [comment]
So, I'm not a huge fan of Bower, but I know a lot of folks use it. I just went on their site to check their registry and see if the name was available. Turns out, a single user is using both the names `typer` and `typer-js` to point to the _same_ registry. So they're pretty much squatting on names. Not the thing to do. I left an [issue](https://github.com/123apps/typer.js/issues/2) on that person's repo asking them to free up one of the names. We'll see how that goes. If they free up the name relatively soon, then I'll consider throwing this library on Bower. Sorry about that.

**Comment by qodesmith** [comment]
No go on the name. Bower will have to wait for now.
